### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [etwasmitbaum/Phase10Counter#10]
ref: https://github.com/etwasmitbaum/Phase10Counter/blob/v16_Pre-Release/app/build.gradle#L96 it might be FOSS but depends on GMS which is not FOSS :(

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/0e94fad5091d08eee6f230ec7ad01d024192f391

**Comment by licaon-kter** [comment]
Some alternatives: https://github.com/ViliusSutkus89/pdf2htmlEX-Android/issues/34#issue-1067754331

**Comment by linsui** [comment]
See also https://gitlab.com/-/snippets/1896503#license-dialogs. [AboutLibraries](https://github.com/mikepenz/AboutLibraries) is the go-to solution.

**Comment by etwasmitbaum** [comment]
Oh my, thank you very much!
I did not think about that. I will change this immediately!

**Comment by etwasmitbaum** [comment]
I am stuck at properly implementing a new solution. Need more time for it. Probably a few days.
Sorry for the inconvenience.

**Comment by etwasmitbaum** [comment]
I just figured it out, sorry guys. New release incoming.
It's the Legacy implementation of AboutLibraries. But this one I got working the fastest.

**Comment by licaon-kter** [comment]
Thanks https://gitlab.com/fdroid/fdroiddata/-/commit/14c687ee7b515b4c552656fb413578e7ef31c076

**Comment by etwasmitbaum** [comment]
You're welcome!
Thank you for making me aware!
