### ISSUE TITLE
Feature request: remember late time players 

### ISSUE THREAD

**Issue by kidexx** [etwasmitbaum/Phase10Counter#9]
Hi,
not an issue, a feature request:

Can you or someone else please add a function to remember last played game payer names instead of starting completely fresh each time?

For a non programmer a cool app by the way, I like those minimalistic but functional apps!

**Comment by etwasmitbaum** [comment]
Hi,
I'm glad you like my app! Thank you for the feature request.
I just looked into it, and it was much easier to implement than I expected. 
However, I haven't done extensive testing yet, so there might be unexpected issues. 
I will push the code soon and probably make a pre-release so that you can test it if you'd like.

**Comment by kidexx** [comment]
Cool, that was quick, thanks, let me know when the new version is available in f-droid, I can test it then.

**Comment by etwasmitbaum** [comment]
So I quickly made a pre-release. I don't think this will be published to F-Droid, unless I make it a full release.
In the meantime you can download the F-Droid apk from here: https://github.com/etwasmitbaum/Phase10Counter/releases/tag/v15_Pre-Release
This should work with no issue. But I would not recommend installing this version, if you have a current game running.

**Comment by kidexx** [comment]
It did not installed it, maybe because the version number is the same? :

![Screenshot_20230612_085132_com mixplorer-picsay](https://github.com/etwasmitbaum/Phase10Counter/assets/16257028/b019c643-5d89-4a0c-9eaa-c2fa56818291)

**Comment by etwasmitbaum** [comment]
I am sorry. Forgot to increase the version number.
Here is a new release: https://github.com/etwasmitbaum/Phase10Counter/releases/tag/v16_Pre-Release

**Comment by kidexx** [comment]
Hi, I updated it, unfortunately it does not keep the names after finishing the game.

**Comment by etwasmitbaum** [comment]
Hi, that's not good. It is working for me just fine.
Maybe I missunderstood the feature you requested?
What I implemented is: If you click the "End match" button, click yes on the dialog. You will be back to the screen to add new players. In this screen there should be all the players of the match you just ended.

If this does not work for you, could you provide information abour your phone, OS and the names of the players?

PS: I released a new version just this morning. Maybe this works for you?
